// ===== 抽取自 game.js 的纯数据（自动生成，请勿手改） =====
const FACTIONS = {
  '剑气长城': '#c0392b',
  '中土文庙': '#2980b9',
  '蛮荒天下': '#8e44ad',
  '青冥天下': '#16a085',
  '莲花天下': '#d4a017',
  '散修': '#7f8c8d',
};

const HOSTILE = {
  '剑气长城':'蛮荒天下', '中土文庙':'蛮荒天下', '青冥天下':'蛮荒天下',
  '莲花天下':'蛮荒天下', '蛮荒天下':'剑气长城', '散修':'蛮荒天下',
};

const CHARS = {
  chenpingan:  { name:'陈平安', faction:'散修', hp:4, realm:'止境', skills:['守拙','问心','攒劲'], flagship:true,
    txt:'【守拙】成为「剑气」目标时，可弃一张牌视为打出「守心」；【问心】每回合首次造成伤害后，可令目标「讲道理」，你方道理大则目标弃一牌；【攒劲】每使用第三张「丹药」，永久 +1 手牌上限' },
  caoci:       { name:'曹慈', faction:'散修', hp:5, realm:'止境武夫', skills:['慈','武'], flagship:true,
    txt:'【慈】你受到伤害时反弹 1 点给来源（每回合限一次）；【武】近战「剑气」伤害 +1（裴杯之徒）' },
  ningyao:     { name:'宁姚', faction:'剑气长城', hp:3, realm:'止境', skills:['剑心','镇蛮'], flagship:true,
    txt:'【剑心】你打出的「剑气」不可被「守心」抵消（仍可被装备/神通抵）；【镇蛮】你对蛮荒天下角色伤害 +1' },
  aliang:      { name:'阿良', faction:'剑气长城', hp:4, realm:'十四境', skills:['问剑','无忧'], flagship:true, sword:'饮者',
    txt:'【问剑】出牌阶段指定一名角色，其直到回合结束不能使用「守心」；【无忧】受伤害时展示手牌，若全为「剑气」则免伤并摸一' },
  miyu:        { name:'米裕', faction:'剑气长城', hp:3, realm:'玉璞境', skills:['米','杀力'], flagship:true, sword:'霞满天',
    txt:'【米】你的「剑气」基础伤害视为 2；【杀力】你对蛮荒天下角色伤害再 +1' },
  chenqingdu:  { name:'陈清都', faction:'剑气长城', hp:4, realm:'十四境', skills:['一剑','长城'], flagship:true, sword:'浮萍',
    txt:'【一剑】出牌阶段弃所有手牌，对一名角色造 X 伤（X=弃牌数且≥其气血一半），每局限一次；【长城】非剑气长城角色须先击败另一名剑气长城角色，才能以你为攻击目标' },
  baiye:       { name:'白也', faction:'散修', hp:3, realm:'十四境·合道', skills:['诗剑','青衫'], flagship:true,
    // 原著：浩然天下诗剑第一人，十四境合道诗篇，持仙剑太白；曾提剑援手剑气长城，非长城出身。
    txt:'【诗剑】每打出一张「锦囊」，本回合剑气伤害 +1（可叠加）；【青衫】无视距离使用「剑气」' },
  qijingchun:  { name:'齐静春', faction:'中土文庙', hp:3, realm:'玉璞境', skills:['教化','护道'], flagship:true,
    txt:'【教化】回合结束给一名队友一张牌；若其为儒修额外摸一；【护道】一名阵营角色即将受伤时，你可弃一牌替其承 1 点' },
  lisan:       { name:'礼圣', faction:'中土文庙', hp:4, realm:'飞升', skills:['礼法','规矩'], flagship:true,
    txt:'【礼法】其他角色打出的第一张「锦囊」对你无效，除非其先对你「陈词」成功；【规矩】开局指定一条永久规矩（如"不得使用蛮荒入侵"），违反者受 1 伤' },
  zhoumi:      { name:'周密', faction:'蛮荒天下', hp:5, realm:'飞升', skills:['算计','化外'], flagship:true,
    txt:'【算计】出牌阶段获得一名角色一张手牌（每局限数次）；【化外】免疫第一次「讲道理」判定失败的效果' },
  baize:       { name:'白泽', faction:'蛮荒天下', hp:3, realm:'止境', skills:['通晓','旁观'], flagship:true,
    txt:'【通晓】你可知所有角色的大道属性；你的「讲道理」判定 +1；【旁观】你不能被选为「锦囊」目标，除非该锦囊指定所有角色' },
  daozu:       { name:'道祖', faction:'青冥天下', hp:4, realm:'飞升', skills:['道法自然','无为'], flagship:true,
    txt:'【道法自然】出牌阶段弃两张摸两张；若弃牌含「锦囊」额外摸一；【无为】回合外受到的第一次伤害 -1' },
  fozu:        { name:'佛祖', faction:'莲花天下', hp:4, realm:'飞升', skills:['因果','慈悲'], flagship:true,
    txt:'【因果】一名角色对你造成伤害时，你可将 1 点伤害反弹给伤害来源；【慈悲】你的「丹药」可同时回复两名角色各 1 气血' },
  '左右': { name:'左右', faction:'剑气长城', hp:3, realm:'飞升', skills:['出城','剑仙'], txt:'【出城】你对攻击范围外的角色造成伤害 +1；【剑仙】手牌上限 +1', talent:'锋芒' },
  '魏晋': { name:'魏晋', faction:'剑气长城', hp:3, realm:'止境', skills:['浩然','孤峰'], txt:'【浩然】场上有宁姚时，你的剑气伤害 +1；【孤峰】手牌上限 +2', talent:'锋芒' },
  '董三更': { name:'董三更', faction:'剑气长城', hp:3, realm:'止境', skills:['三更','夜'], txt:'【三更】每回合你打出的第 3 张「剑气」伤害 +1；【夜】回合外打出的「守心」视为 +1 次', talent:'锋芒' },
  '姚近之': { name:'姚近之', faction:'剑气长城', hp:3, realm:'止境', skills:['近之','柔剑'], txt:'【近之】场上有魏晋时，双方剑气伤害各 +1；【柔剑】一张「守心」可当「剑气」使用', talent:'锋芒' },
  '齐廷济': { name:'齐廷济', faction:'剑气长城', hp:3, realm:'止境', skills:['齐家剑','廷'], txt:'【齐家剑】出牌阶段限一次，额外打出一张「剑气」；【廷】你的判定点数 +1', talent:'锋芒' },
  '隋右边': { name:'隋右边', faction:'剑气长城', hp:3, realm:'止境', skills:['右边','隋'], txt:'【右边】受伤时可弃一张牌免 1 伤（每回合限一次）；【隋】与隋景澄互保，一方受伤另一方可替', talent:'锋芒' },
  // 本命飞剑「抱朴」「北斗」（原著，北斗主死）。旧写「芝兰/早逝」是按人物气质所拟、非飞剑名，已归位；机制与数值不变。
  '陆芝': { name:'陆芝', faction:'剑气长城', hp:3, realm:'止境', skills:['抱朴','北斗'], sword:'抱朴·北斗', txt:'【抱朴】回合结束给一名队友一张牌；【北斗】你死亡时令一名队友摸两张', talent:'锋芒' },
  // 持剑者：旧天庭五至高之一，非剑气长城出身；卡池阵营用「散修」压缩。
  '持剑者': { name:'持剑者', faction:'散修', hp:5, realm:'十四境', skills:['至高','剑源'], flagship:true, talent:'机缘', txt:'【至高】你免疫「论道」「讲道理」等言语类控制；【剑源】你的「剑气」伤害 +1，且无视「守心」抵消（可被装备/神通抵挡）' },
  '陈熙': { name:'陈熙', faction:'剑气长城', hp:3, realm:'止境', skills:['熙','城'], txt:'【熙】本命飞剑「祭炼」成长速度翻倍（每次祭炼攻击 +1）；【城】剑气命中后摸一', talent:'锋芒' },
  // 原著用字：萧愻（前任隐官）。旧 key「萧𢙏」已废弃；立绘文件名亦为萧愻.jpg。
  '萧愻': { name:'萧愻', faction:'剑气长城', hp:3, realm:'止境', skills:['愻'], txt:'【愻】「剑气」命中后，可立即再打出一张「剑气」（每回合限一次）（剑气长城前隐官）', talent:'锋芒' },
  '老秀才': { name:'老秀才', faction:'中土文庙', hp:4, realm:'飞升', skills:['文','圣'], txt:'【文】全场儒修手牌上限 +1；【圣】游戏开始时每人获得一张牌', talent:'耕读' },
  '亚圣': { name:'亚圣', faction:'中土文庙', hp:4, realm:'止境', skills:['守礼','亚'], txt:'【守礼】每局限一次免疫一张「锦囊」；【亚】儒修技能效果 +1', talent:'耕读' },
  '至圣先师': { name:'至圣先师', faction:'中土文庙', hp:5, realm:'飞升', skills:['至圣','先师'], txt:'【至圣】每名儒修每回合限一次多摸一；【先师】你死亡时全场儒修回 1 气血', talent:'耕读' },
  '崔瀺': { name:'崔瀺', faction:'中土文庙', hp:4, realm:'飞升', skills:['算无遗策','国士无双'], txt:'【算无遗策】每回合限一次，观看一名角色两张手牌并交换其中一张；【国士无双】你每回合首次造成伤害时，可令一名同阵营角色摸一张牌', talent:'耕读' },
  '崔诚': { name:'崔诚', faction:'中土文庙', hp:4, realm:'飞升', skills:['传道','严教'], txt:'【传道】每回合限一次，可令一名同阵营角色视为使用一张基本牌；【严教】你对同阵营角色造成伤害时，可令其改为摸一张牌', talent:'耕读' },
  '崔东山': { name:'崔东山', faction:'中土文庙', hp:3, realm:'止境', skills:['观棋','分身'], txt:'【观棋】出牌阶段开始时可观看任意一名角色的手牌顶一张；【分身】你受到致命伤害时，可弃两张牌令伤害改为1', talent:'耕读' },
  '君倩': { name:'君倩', faction:'中土文庙', hp:3, realm:'止境', skills:['君子','倩'], txt:'【君子】出牌阶段可各打出一张「剑气」与一张「守心」；【倩】儒修对你的「剑气」伤害 -1', talent:'耕读' },
  '周澄': { name:'周澄', faction:'中土文庙', hp:3, realm:'止境', skills:['澄','文'], txt:'【澄】你的判定阶段可将判定牌替换为你的一张手牌；【文】锦囊点数 +1', talent:'耕读' },
  '李宝瓶': { name:'李宝瓶', faction:'中土文庙', hp:3, realm:'练气', skills:['宝瓶','问学'], txt:'【宝瓶】摸牌阶段多摸一；【问学】出牌阶段给一名队友一张牌（每回合限一次）', talent:'耕读' },
  '林守一': { name:'林守一', faction:'中土文庙', hp:3, realm:'止境', skills:['守一','算'], txt:'【守一】你的判定点数 +1；【算】一张「锦囊」可当「破阵」或「借物」使用', talent:'耕读' },
  '张山峰': { name:'张山峰', faction:'中土文庙', hp:4, realm:'止境', skills:['山峰','厚'], txt:'【山峰】每局限一次受到伤害 -1；【厚】你的手牌上限 +1', talent:'耕读' },
  '顾粲': { name:'顾璨', faction:'散修', hp:3, realm:'止境', skills:['棋子','蛊'], txt:'【棋子】弃一牌当「锦囊」指定一名角色下回合无法出「剑气」；【蛊】你受伤害时反弹 1 点给来源（每局限一次）', talent:'机缘' },
  '宋集薪': { name:'宋集薪', faction:'中土文庙', hp:3, realm:'止境', skills:['集薪','弃文'], txt:'【集薪】手牌上限 +2；【弃文】一张手牌可当任意「基本牌」使用', talent:'耕读' },
  '杨老头': { name:'杨老头', faction:'散修', hp:4, realm:'飞升', skills:['棋','师'], txt:'【棋】任意角色的判定结算前，你可改其中一张判定牌；【师】陈平安在场时双方互保，各免 1 伤（每局限一次）', talent:'机缘' },
  // 原著：青童天君，骊珠洞天暗线布局者；郑大风之师。非中土文庙。
  '李槐': { name:'李槐', faction:'中土文庙', hp:3, realm:'练气', skills:['槐','问学'], txt:'【槐】摸牌阶段可弃一张牌，令一名队友本回合手牌上限 +1；【问学】出牌阶段给一名队友一张牌', talent:'耕读' },
  '刘重润': { name:'刘重润', faction:'蛮荒天下', hp:3, realm:'止境', skills:['龙女','润'], txt:'【龙女】每局限一次，受到致命伤时免伤并回 1；【润】出牌阶段给一名队友一张牌', talent:'嗜血' },
  '之祠': { name:'之祠', faction:'蛮荒天下', hp:4, realm:'止境', skills:['神祠','祠'], txt:'【神祠】你的回合结束回 1 气血（不超过上限）；【祠】一张「锦囊」可当「守心」使用', talent:'嗜血' },
  '斐然': { name:'斐然', faction:'蛮荒天下', hp:4, realm:'飞升', skills:['画','妖'], txt:'【画】弃两张牌，创造一张临时「锦囊」并立即结算；【妖】你对中土文庙角色伤害 +1', talent:'嗜血' },
  '老瞎子': { name:'老瞎子', faction:'蛮荒天下', hp:4, realm:'止境', skills:['盲','老'], txt:'【盲】你的「剑气」无视距离；【老】每局限一次受到伤害 -1', talent:'嗜血' },
  // 十四王座之首。原著又称「妖族大祖」「蛮荒大祖」，与旧条目 manhuangdazu 为同一人，已合并。
  '托月山': { name:'托月山大祖', faction:'蛮荒天下', hp:5, realm:'飞升', skills:['山','托月'], txt:'【山】气血上限视为 5；【托月】受伤时反弹 1 点给来源（每局限一次）', talent:'嗜血' },
  '纳兰烧苇': { name:'纳兰烧苇', faction:'蛮荒天下', hp:4, realm:'止境', skills:['烧苇','苇'], txt:'【烧苇】你的「剑气」附加 1 点火属性伤害；【苇】火伤对青冥天下额外 +1', talent:'嗜血' },
  '老聋儿': { name:'老聋儿', faction:'蛮荒天下', hp:4, realm:'止境', skills:['聋','儿'], txt:'【聋】免疫语言类「锦囊」（论道、陈词等）；【儿】手牌上限 +1', talent:'嗜血' },
  '仰止': { name:'仰止', faction:'蛮荒天下', hp:4, realm:'止境', skills:['仰','止'], txt:'【仰】你的攻击范围 +1；【止】被你攻击的角色下回合无法使用「守心」', talent:'嗜血' },
  '龙君': { name:'龙君', faction:'蛮荒天下', hp:5, realm:'飞升', skills:['龙君','君'], txt:'【龙君】全场蛮荒天下角色造成的伤害 +1；【君】你死亡时全体蛮荒角色各摸两张', talent:'嗜血' },
  '搬山猿': { name:'搬山猿', faction:'蛮荒天下', hp:4, realm:'止境', skills:['搬山','猿'], txt:'【搬山】你的「剑气」伤害 +1，但不可指定气血 1 的角色；【猿】每局限一次，受到致命伤时免伤', talent:'嗜血' },

  /* 蛮荒天下·旧十四王座补全（依百度百科「十四王座」、中文百科全书同名词条）
     完整名录：托月山大祖·周密·刘叉·袁首·仰止·绯妃·黄鸾·牛刀·五嶽·白莹·曜甲·切韵·龙君·荷花庵主
     其中 托月山大祖 / 周密 / 龙君 / 仰止 已在上方，此处补齐其余十席。 */
  '刘叉': { name:'刘叉', faction:'蛮荒天下', hp:4, realm:'飞升', skills:['问剑','佩刀'], txt:'【问剑】出牌阶段指定一名角色，其直到回合结束不能使用「守心」；【佩刀】你的「剑气」命中后摸一', talent:'嗜血' },
  '袁首': { name:'袁首', faction:'蛮荒天下', hp:4, realm:'飞升', skills:['搬山','石珠'], txt:'【搬山】你的「剑气」伤害 +1；【石珠】每局限一次，受到致命伤时免伤', talent:'嗜血' },
  '五嶽': { name:'五嶽', faction:'蛮荒天下', hp:5, realm:'飞升', skills:['六臂','神到'], txt:'【六臂】出牌阶段限一次，额外打出一张「剑气」；【神到】你每回合受到的第一次伤害 -1', talent:'嗜血' },
  '牛刀': { name:'牛刀', faction:'蛮荒天下', hp:4, realm:'飞升', skills:['金甲','蛮牛'], txt:'【金甲】你每回合受到的第一次伤害 -1（金甲亦是牢狱）；【蛮牛】你的「剑气」伤害 +1', talent:'嗜血' },
  '白莹': { name:'白莹', faction:'蛮荒天下', hp:4, realm:'飞升', skills:['枯骨','傀儡'], txt:'【枯骨】你死亡时令一名蛮荒天下队友摸一张；【傀儡】手牌上限 +1', talent:'嗜血' },
  '绯妃': { name:'绯妃', faction:'蛮荒天下', hp:3, realm:'飞升', skills:['水运','蛇蜕'], txt:'【水运】你的回合结束回 1 气血（不超过上限）；【蛇蜕】每局限一次受到伤害 -1', talent:'嗜血' },
  '曜甲': { name:'曜甲', faction:'蛮荒天下', hp:3, realm:'飞升', skills:['金精','倒悬'], txt:'【金精】你的装备牌效果对所有角色 +1；【倒悬】每局限一次受到伤害 -1', talent:'嗜血' },
  '切韵': { name:'切韵', faction:'蛮荒天下', hp:4, realm:'飞升', skills:['养剑葫','面皮'], txt:'【养剑葫】「剑气」命中后，可立即再打出一张「剑气」（每回合限一次）；【面皮】免疫语言类「锦囊」（论道、陈词等）', talent:'嗜血' },
  '黄鸾': { name:'黄鸾', faction:'蛮荒天下', hp:3, realm:'飞升', skills:['洞府','鸾翼'], txt:'【洞府】你的装备牌效果对所有角色 +1；【鸾翼】你的攻击范围 +1', talent:'嗜血' },
  '荷花庵主': { name:'荷花庵主', faction:'蛮荒天下', hp:4, realm:'飞升', skills:['月魄','庵主'], txt:'【月魄】你的回合结束回 1 气血（不超过上限）；【庵主】你的判定点数 +1', talent:'嗜血' },
  '余斗': { name:'余斗', faction:'青冥天下', hp:3, realm:'止境', skills:['斗转','星移'], txt:'【斗转】你打出的「锦囊」结算后可回收手牌；【星移】你与其他角色距离 -1（攻击范围 +1）', talent:'无为' },
  '陆沉': { name:'陆沉', faction:'青冥天下', hp:3, realm:'止境', skills:['一气化三清','沉静'], txt:'【一气化三清】限定技：获得攻/守/变三枚标记，每回合激活一枚（攻：本回合剑气+1；守：免1伤；变：弃牌摸牌）；【沉静】一张「闪」可当「守心」或「剑气」', talent:'无为' },
  '阮秀': { name:'阮秀', faction:'散修', hp:3, realm:'止境', skills:['炼器','火属'], txt:'【炼器】出牌阶段消耗两张牌铸一把临时「本命飞剑」（攻击 +1，可成长）；【火属】你的「剑气」对蛮荒角色额外造成 1 点火伤', talent:'机缘' },
  // 原著：趴地峰火龙真人，张山峰之师；卡内「本命飞剑·火龙」为机制名，勿与阮邛混写。
  '火龙真人': { name:'火龙真人', faction:'散修', hp:4, realm:'止境', skills:['铸剑','火德'], sword:'火龙', txt:'【铸剑】开局获得专属「本命飞剑·火龙」；【火德】你的装备牌效果对所有角色 +1（趴地峰·张山峰之师）', talent:'机缘' },
  '裴钱': { name:'裴钱', faction:'散修', hp:3, realm:'止境武夫', skills:['钱','学徒'], txt:'【钱】摸牌阶段多摸一（机灵）；【学徒】陈平安在场时你的剑气伤害 +1', talent:'机缘' },
  '刘羡阳': { name:'刘羡阳', faction:'散修', hp:4, realm:'止境', skills:['炼','阳'], txt:'【炼】出牌阶段铸一把装备（攻击 +1）；【阳】每局限一次受伤 -1', talent:'机缘' },
  '李二': { name:'李二', faction:'散修', hp:4, realm:'止境', skills:['武夫','二'], txt:'【武夫】你的「剑气」视为近战武力，不可被「守心」抵消，伤害 +1；【二】受伤害 -1（每局限一次）', talent:'机缘' },
  '李柳': { name:'李柳', faction:'散修', hp:3, realm:'止境', skills:['柳','柔'], txt:'【柳】每局限一次完全免伤；【柔】一张「守心」可当「剑气」', talent:'机缘' },
  '朱敛': { name:'朱敛', faction:'散修', hp:4, realm:'止境', skills:['敛','管家'], txt:'【敛】你的手牌不向其他角色暴露，且可暗藏一张牌；【管家】出牌阶段给队友一张牌', talent:'机缘' },
  '姜尚真': { name:'姜尚真', faction:'散修', hp:3, realm:'玉璞境', skills:['尚真','真'], txt:'【尚真】出牌阶段弃一牌摸一（交易）；【真】你的装备牌消耗 -1（玉圭宗宗主/落魄山首席供奉）', talent:'机缘' },
  '姜赦': { name:'姜赦', faction:'散修', hp:3, realm:'止境', skills:['赦'], txt:'【赦】每回合限一次，获得一名角色一张手牌（赦令）', talent:'机缘' },
  '南簪': { name:'南簪', faction:'散修', hp:3, realm:'止境', skills:['簪','南'], txt:'【簪】你的判定点数 +1；【南】手牌上限 +1', talent:'机缘' },
  '卢白象': { name:'卢白象', faction:'散修', hp:4, realm:'止境', skills:['白象','卢'], txt:'【白象】每局限一次受伤 -1；【卢】攻击范围 +1', talent:'机缘' },
  '刘灞桥': { name:'刘灞桥', faction:'散修', hp:3, realm:'止境', skills:['灞桥'], txt:'【灞桥】出牌阶段可额外打出一张「基本牌」', talent:'机缘' },
  '谢松花': { name:'谢松花', faction:'散修', hp:3, realm:'止境', skills:['松花','谢'], txt:'【松花】「剑气」命中后摸一；【谢】守心 +1', talent:'机缘' },
  '谢狗': { name:'谢狗', faction:'散修', hp:3, realm:'飞升境', skills:['狗'], txt:'【狗】受伤时若手牌有「守心」则免 1 伤（每回合限一次）（落魄山供奉·化名白景·飞升境）', talent:'机缘' },
  '贺小凉': { name:'贺小凉', faction:'散修', hp:3, realm:'止境', skills:['小凉'], txt:'【小凉】你的判定牌可重掷一次', talent:'机缘' },
  '赊月': { name:'赊月', faction:'散修', hp:3, realm:'止境', skills:['赊'], txt:'【赊】出牌阶段获得一名角色一张牌，下回合须还回（否则受 1 伤）', talent:'机缘' },
  '郑居中': { name:'郑居中', faction:'散修', hp:3, realm:'止境', skills:['居中','郑'], txt:'【居中】手牌上限 +1；【郑】判定 +1', talent:'机缘' },
  '郭竹酒': { name:'郭竹酒', faction:'散修', hp:3, realm:'止境', skills:['竹酒','郭'], txt:'【竹酒】「问剑（酒）」效果 +1；【郭】出牌阶段可弃一牌回 1 气血', talent:'机缘' },
  '长命': { name:'长命', faction:'散修', hp:3, realm:'止境', skills:['长命'], txt:'【长命】你的「桃」回复 +1（回 2）', talent:'机缘' },
  '徐远霞': { name:'徐远霞', faction:'散修', hp:3, realm:'止境', skills:['远霞','徐'], txt:'【远霞】攻击范围 +1；【徐】', talent:'机缘' },
  '小陌': { name:'小陌', faction:'散修', hp:3, realm:'飞升境', skills:['陌'], txt:'【陌】出牌阶段给一名队友一张牌（每回合限一次）（落魄山一等供奉·飞升境）', talent:'机缘' },
  '苏稼': { name:'苏稼', faction:'散修', hp:3, realm:'止境', skills:['稼'], txt:'【稼】摸牌阶段多摸一', talent:'机缘' },
  '裴杯': { name:'裴杯', faction:'散修', hp:3, realm:'止境', skills:['杯'], txt:'【杯】出牌阶段弃一牌令一名角色摸一（中土神州女子武夫·曹慈之师）', talent:'机缘' },
  '陈景清': { name:'陈景清', faction:'散修', hp:3, realm:'止境', skills:['景清'], txt:'【景清】每回合首张「锦囊」不计入次数', talent:'机缘' },
  '陈暖树': { name:'陈暖树', faction:'散修', hp:3, realm:'练气', skills:['暖树'], txt:'【暖树】出牌阶段给陈平安一张牌', talent:'机缘' },
  '隋景澄': { name:'隋景澄', faction:'散修', hp:3, realm:'止境', skills:['景澄','隋'], txt:'【景澄】与隋右边互保，一方受伤另一方可替；【隋】', talent:'机缘' },
  '魏檗': { name:'魏檗', faction:'散修', hp:4, realm:'止境', skills:['山君','檗'], txt:'【山君】出牌阶段指定一名角色，其下回合摸牌阶段少摸一（地形压制）；【檗】受伤害 -1（每局限一次）', talent:'机缘' },
  '魏羡': { name:'魏羡', faction:'散修', hp:3, realm:'止境', skills:['羡'], txt:'【羡】每回合限一次获得一名角色一张手牌', talent:'机缘' },
  '黄庭': { name:'黄庭', faction:'散修', hp:3, realm:'止境', skills:['黄庭'], txt:'【黄庭】你的装备不可被「破阵」弃置', talent:'机缘' },
  '周海镜': { name:'周海镜', faction:'散修', hp:3, realm:'止境', skills:['海镜'], txt:'【海镜】出牌阶段查看一名角色的手牌', talent:'机缘' },
  '周米粒': { name:'周米粒', faction:'散修', hp:2, realm:'练气', skills:['米粒'], txt:'【米粒】每回合限一次随机「机缘」摸一（随机基本/锦囊）', talent:'机缘' },
  '石柔': { name:'石柔', faction:'散修', hp:3, realm:'练气', skills:['蜕','窥'], txt:'【蜕】你受到的伤害 -1（每局限一次，仙人遗蜕替人挡灾）；【窥】你的判定 +1（那双被人借过的眼睛，看得比旁人清楚些）', talent:'机缘' },
  '稚圭': { name:'稚圭', faction:'散修', hp:3, realm:'止境', skills:['稚圭'], txt:'【稚圭】每局限一次完全免伤', talent:'机缘' },
  '宋雨烧': { name:'宋雨烧', faction:'散修', hp:3, realm:'止境', skills:['雨烧'], txt:'【雨烧】你的「剑气」火伤 +1', talent:'机缘' },
  '沛湘': { name:'沛湘', faction:'散修', hp:3, realm:'止境', skills:['沛','湘'], txt:'【沛】一张「守心」可当两张用（水柔）；【湘】', talent:'机缘' },
  '柳柔': { name:'柳柔', faction:'散修', hp:3, realm:'止境', skills:['柔'], txt:'【柔】一张「守心」可当「剑气」使用', talent:'机缘' },
  '陆台': { name:'陆台', faction:'散修', hp:3, realm:'止境', skills:['陆台'], txt:'【陆台】每回合限一次受伤反弹 1 点', talent:'机缘' },
  '马苦玄': { name:'马苦玄', faction:'散修', hp:3, realm:'止境', skills:['苦玄','玄'], txt:'【苦玄】你的「讲道理」判定 +1；【玄】对陈平安造成的伤害 +1', talent:'机缘' },
  '于玄': { name:'于玄', faction:'散修', hp:3, realm:'止境', skills:['于玄'], txt:'【于玄】出牌阶段弃两张摸两张（循环）', talent:'机缘' },
  '吴霜降': { name:'吴霜降', faction:'散修', hp:3, realm:'止境', skills:['霜降'], txt:'【霜降】「剑气」命中后，目标下回合出牌阶段少出一张牌（冻结）', talent:'机缘' },
  '苏心斋': { name:'苏心斋', faction:'散修', hp:3, realm:'止境', skills:['心斋'], txt:'【心斋】一张「守心」视为 +1 次', talent:'机缘' },
  '郦彩': { name:'郦彩', faction:'散修', hp:3, realm:'止境', skills:['郦彩'], txt:'【郦彩】摸牌阶段多摸一', talent:'机缘' },

  // 新增：原著真实人物补全
  '李希圣': { name:'李希圣', faction:'中土文庙', hp:3, realm:'止境', skills:['希圣','兄'], txt:'【希圣】儒修队友手牌上限 +1；【兄】李宝瓶在场时，你可替她承受 1 点伤害', talent:'耕读' },
  '赵繇': { name:'赵繇', faction:'中土文庙', hp:3, realm:'止境', skills:['繇印','静春'], txt:'【繇印】你的判定牌点数 +2；【静春】你死亡时，可令一名儒修队友摸两张牌', talent:'耕读' },
  '宋长镜': { name:'宋长镜', faction:'散修', hp:5, realm:'止境', skills:['长镜','武运'], txt:'【长镜】你受到伤害时，可弃一张牌令伤害 -1；【武运】你的「剑气」伤害 +1', talent:'机缘' },
  // 原著：大骊宋氏皇族武道宗师，非中土文庙。
  '阮邛': { name:'阮邛', faction:'散修', hp:4, realm:'止境', skills:['铸剑','护女'], txt:'【铸剑】出牌阶段可弃两张牌，铸造一把临时「本命飞剑」（攻击 +1，可成长）；【护女】阮秀在场时，你的装备牌效果 +1', talent:'机缘' },
  '蔡金简': { name:'蔡金简', faction:'散修', hp:3, realm:'止境', skills:['断桥','金简'], txt:'【断桥】你对陈平安造成伤害时，该伤害 +1；【金简】你的「剑气」可令目标本回合无法使用「守心」', talent:'机缘' },
  '董水井': { name:'董水井', faction:'散修', hp:3, realm:'练气', skills:['井','商'], txt:'【井】摸牌阶段可观看牌堆顶一张牌并选择是否置于牌堆底；【商】出牌阶段可与一名角色交换一张手牌', talent:'机缘' },
  'mihu': { name:'米祜', faction:'剑气长城', hp:3, realm:'止境', skills:['守门','米家'], txt:'【守门】镇守剑气长城城门，米家剑专破妖族；【米家】同米裕一脉，对蛮荒天下角色剑气伤害 +1', talent:'锋芒' },
  'nalanyexing': { name:'纳兰夜行', faction:'剑气长城', hp:3, realm:'止境', skills:['夜行','纳兰'], txt:'【夜行】夜战剑势连绵，一剑既出常再递一剑；【纳兰】纳兰家剑修，追击凌厉', talent:'锋芒' },
  'longhushan': { name:'龙虎山老天师', faction:'青冥天下', hp:4, realm:'飞升', skills:['天师','斩龙'], txt:'【天师】执掌龙虎山道门祖庭道统；【斩龙】正阳山便由其门下分出，同源而道争' },
  'liulaocheng': { name:'刘老成', faction:'散修', hp:3, realm:'止境', skills:['书简湖','老成'], txt:'【书简湖】书简湖一脉老辈，胸有丘壑；【老成】久历世事，判定点数 +1', talent:'机缘' },

  // 新增：原著真实人物补全（第二批）
  xunyuan:      { name:'荀渊', faction:'散修', hp:3, realm:'飞升境', skills:['一尺枪','余家贫'], txt:'【一尺枪】你的「剑气」伤害 +1（一尺枪，一寸短一寸险）；【余家贫】每回合限一次，受到伤害 -1', talent:'锋芒' },
  // 用户原著口径：谢时、老蛟、仙珠 非原著人物，已删卡
  liujinglong:  { name:'刘景龙', faction:'剑气长城', hp:4, realm:'飞升境', skills:['规矩','守序'], sword:'规矩', txt:'【规矩】你的「剑气」无视距离；【守序】一名剑气长城队友受伤时，你可替其承 1 点（旧异名「齐景龙」已合并）', talent:'锋芒' },
  // 勘误：于樾本命飞剑为「惊鸟」「百花」（原著第792章明载），原挂的「北斗」「抱朴」实为陆芝之剑。
  // 原著：流霞洲老剑修（老玉璞），皑皑洲密云谢氏首席客卿、落魄山记名供奉（化名于倒悬）；非剑气长城出身，仅金丹境游历三年。
  yuyue:        { name:'于樾', faction:'散修', hp:3, realm:'玉璞境', skills:['惊鸟','百花'], sword:'惊鸟·百花', txt:'【惊鸟】以风驰电掣著称，你的攻击范围 +1；【百花】出牌阶段限一次，额外打出一张「剑气」', talent:'锋芒' },

  '曹晴朗': { name:'曹晴朗', faction:'散修', hp:3, realm:'金丹境', skills:['三元','读书'], txt:'【三元】摸牌阶段多摸一（南苑国科举连中三元、大骊科举榜眼，厚积薄发）；【读书】判定 +1（文圣一脉真正的读书种子）' },
  '赵树下': { name:'赵树下', faction:'散修', hp:4, realm:'五境武夫', skills:['百万拳','走桩'], txt:'【百万拳】你打出的「剑气」伤害 +1（两百万次基础拳法打下的底子）；【走桩】摸牌阶段多摸一（六步走桩，走满十万遍）' },
  '宁吉':   { name:'宁吉', faction:'散修', hp:3, realm:'练气', skills:['道胎','开卷'], txt:'【道胎】摸牌阶段多摸一（天生道胎，只要想学，机缘就走到跟前）；【开卷】判定 +1（陆沉赠印「开卷有益」）' },
  '邓剑枰': { name:'邓剑枰', faction:'散修', hp:3, realm:'金丹境', skills:['开山','文脉'], txt:'【开山】你打出的「剑气」伤害 +1（回随驾城收那一对孩子为开山弟子与关门弟子）；【文脉】判定 +1（金丹剑修，却极契合文脉）' },
  '袁黄':   { name:'袁黄', faction:'散修', hp:4, realm:'金身境', skills:['金身','诚拳'], txt:'【金身】你受到伤害 -1（金身境武夫）；【诚拳】你打出的「剑气」伤害 +1（学拳之心诚挚，打破了师父不再收徒的规矩）' },
  '郑大风': { name:'郑大风', faction:'散修', hp:5, realm:'山巅境', skills:['守门','大霜'], txt:'【守门】你受到伤害 -1（落魄山首任看门人，曾是浩然天下最强八境武夫）；【大霜】摸牌阶段多摸一（前身东天门守卫神将，披一身大霜宝甲）' },
  '韦文龙': { name:'韦文龙', faction:'散修', hp:3, realm:'金丹境', skills:['术算','泉府'], txt:'【术算】摸牌阶段多摸一（术算天才）；【泉府】手牌上限 +1（执掌落魄山泉府，管着山上的钱袋子）' },

  '郭稼': { name:'郭稼', faction:'剑气长城', hp:3, realm:'玉璞境', skills:['家剑','祭奠'], talent:'锋芒', txt:'【家剑】你的「剑气」对蛮荒角色伤害 +1（长城郭家）；【祭奠】出牌阶段可弃一张牌，令一名队友摸一张' },
  '叠嶂': { name:'叠嶂', faction:'剑气长城', hp:3, realm:null, skills:['酒铺','叠嶂'], talent:'锋芒', txt:'【酒铺】摸牌阶段多摸一张；【叠嶂】出牌阶段给一名队友一张牌（每回合限一次）' },
  '观照': { name:'观照', faction:'剑气长城', hp:4, realm:null, skills:['问剑','托月'], talent:'锋芒', txt:'【问剑】出牌阶段指定一名角色，其本回合不能使用「守心」（每局限两次）；【托月】每局限一次，你的「剑气」伤害 +2' },
  '陈淳安': { name:'陈淳安', faction:'散修', hp:4, realm:null, skills:['陪都','打落'], talent:'机缘', txt:'【陪都】你受到蛮荒角色伤害 -1（每回合限一次）；【打落】每局限一次，你对蛮荒角色伤害 +2' },
  '邵云岩': { name:'邵云岩', faction:'散修', hp:3, realm:null, skills:['倒悬','嫡传'], talent:'机缘', txt:'【倒悬】摸牌阶段多摸一张；【嫡传】陈平安在场时你的判定 +1' },
  '种秋': { name:'种秋', faction:'散修', hp:3, realm:null, skills:['种','秋'], talent:'机缘', txt:'【种】出牌阶段给一名队友一张牌（每回合限一次）；【秋】你的判定 +1' },
  '刘志茂': { name:'刘志茂', faction:'散修', hp:3, realm:null, skills:['书简','看中'], talent:'机缘', txt:'【书简】出牌阶段可观看一名角色一张手牌；【看中】对「顾粲」（顾璨）伤害 +1' },
  '嫩道人': { name:'嫩道人', faction:'散修', hp:3, realm:null, skills:['嫩','护道'], talent:'机缘', txt:'【嫩】每回合限一次，你受到的伤害 -1；【护道】「李槐」在场时你的手牌上限 +1' },
  '邓剑翘': { name:'邓剑翘', faction:'散修', hp:4, realm:null, skills:['翘','拳'], talent:'机缘', txt:'【翘】你受到伤害 -1（每回合限一次）；【拳】你的「剑气」伤害 +1（女子武夫）' },
  '赵鸾': { name:'赵鸾', faction:'散修', hp:3, realm:null, skills:['鸾','妹'], talent:'机缘', txt:'【鸾】成为「剑气」目标时可弃一张牌视为打出「守心」；【妹】「赵树下」在场时手牌上限 +1' },
  '陈对': { name:'陈对', faction:'散修', hp:3, realm:null, skills:['颍阴','救'], talent:'机缘', txt:'【颍阴】摸牌阶段多摸一张；【救】每局限一次，一名角色濒死时令其回复 1 点气血' },
  '离真': { name:'离真', faction:'蛮荒天下', hp:4, realm:null, skills:['天骄','离'], talent:'嗜血', txt:'【天骄】你的「剑气」伤害 +1；【离】每局限一次，受到致命伤时免伤' },
  '姚冲道': { name:'姚冲道', faction:'剑气长城', hp:3, realm:null, skills:['冲道','联手'], talent:'锋芒', txt:'【冲道】你的「剑气」伤害 +1；【联手】场上有「阿良」时手牌上限 +1' },
  '顾佑': { name:'顾佑', faction:'散修', hp:4, realm:'止境武夫', skills:['佑','止境'], talent:'机缘', txt:'【佑】你受到伤害 -1（每回合限一次）；【止境】你的「剑气」伤害 +1（止境武夫）' },
};

const REALM_LIMIT = { '练气':4, '止境':5, '飞升':6 };

const SKILLS = {
  /* ---------- 剑气长城 ---------- */
  chenqingdu:[{n:'一剑',k:'act',a:'yijian',o:'once',q:'一剑霜寒十四州。',f:'sword'},
              {n:'长城',k:'taunt',q:'长城在，我在。',f:'aura'}],
  ningyao:[{n:'剑心',k:'nododge',q:'剑心通明，守无可守。',f:'sword'},
           {n:'镇蛮',k:'atk',v:1,c:'mang',q:'蛮荒妖族，来一个杀一个。',f:'blood'}],
  aliang:[{n:'问剑',k:'act',a:'wenjian',q:'我叫阿良，善良的良。',qo:1,f:'sword'},
          {n:'无忧',k:'immune',v:'lang',q:'天下第一剑客，无忧无虑。',f:'aura'}],
  miyu:[{n:'米',k:'atk',v:1,q:'米家剑，快。',f:'sword'},
        {n:'杀力',k:'atk',v:1,c:'mang',q:'杀力全开。',f:'blood'}],
  baiye:[{n:'诗剑',k:'atk',v:1,c:'hurt',q:'白也诗无敌，剑亦无敌。',f:'scroll'},
         {n:'青衫',k:'nodist',q:'青衫磊落，剑及天下。',f:'sword'}],
  '左右':[{n:'出城',k:'atk',v:1,c:'far',q:'出城一战，不回头。',f:'sword'},
          {n:'剑仙',k:'hand',v:1,q:'左右为难，仍是剑仙。',f:'aura'}],
  '魏晋':[{n:'浩然',k:'atk',v:1,c:{with:'宁姚'},q:'浩然气，可吞万里。',f:'aura'},
          {n:'孤峰',k:'hand',v:2,q:'孤峰独立，不求人。',f:'aura'}],
  '董三更':[{n:'三更',k:'atk',v:1,c:'third',q:'三更天，该杀人了。',f:'sword'},
            {n:'夜',k:'hand',v:1,q:'夜色如墨，剑光如雪。',f:'sword'}],
  '姚近之':[{n:'近之',k:'atk',v:1,c:{with:'魏晋'},q:'近之，则近之。',f:'sword'},
            {n:'柔剑',k:'useAs',a:'dodge>attack',q:'柔能克刚。',f:'sword'}],
  '齐廷济':[{n:'齐家剑',k:'atkLimit',v:1,q:'齐家剑法，连绵不绝。',f:'sword'},
            {n:'廷',k:'judge',v:1,q:'廷上论剑，寸步不让。',f:'scroll'}],
  mihu:[{n:'守门',k:'reduce',v:1,o:'turn',q:'米家守门，寸步不移。',f:'shield'},
        {n:'米家',k:'atk',v:1,c:'mang',q:'米家剑，斩妖。',f:'blood'}],
  nalanyexing:[{n:'夜行',k:'atk',v:1,c:'far',q:'夜行者，无声而至。',f:'sword'},
               {n:'纳兰',k:'hand',v:1,q:'纳兰家的人，从不多言。',f:'aura'}],

  /* ---------- 中土文庙 ---------- */
  qijingchun:[{n:'教化',k:'act',a:'jiaohua',q:'遇事不决，可问春风。',qo:1,f:'scroll'},
              {n:'护道',k:'reduce',v:1,o:'turn',q:'我为你护道。',f:'shield'}],
  lisan:[{n:'礼法',k:'immune',v:'trick',q:'无规矩，不成方圆。',f:'scroll'},
         {n:'规矩',k:'judge',v:1,q:'此乃礼圣所定。',f:'scroll'}],
  '老秀才':[{n:'文',k:'hand',v:1,q:'读书人的事，能算偷么。',f:'scroll'},
                        {n:'圣',k:'startcard',v:1,q:'人人皆可读书。',f:'scroll'}],
  '亚圣':[{n:'守礼',k:'immune',v:'trick',o:'once',q:'守礼，即守心。',f:'scroll'},
          {n:'亚',k:'judge',v:1,q:'亚圣在此。',f:'scroll'}],
  '至圣先师':[{n:'至圣',k:'draw',v:1,q:'有教无类。',qo:1,f:'scroll'},
              {n:'先师',k:'deathfac',v:1,q:'薪火相传，不可断绝。',f:'lotus'}],
  '崔瀺':[{n:'算无遗策',k:'act',a:'suanji',q:'我崔瀺，算无遗策。',f:'rune'},
          {n:'国士无双',k:'killdraw',v:1,q:'国士无双，当如是。',f:'aura'}],
  '崔诚':[{n:'传道',k:'act',a:'give',q:'道，是要传下去的。',f:'scroll'},
          {n:'严教',k:'reduce',v:1,o:'turn',q:'严师出高徒。',f:'scroll'}],
  '崔东山':[{n:'观棋',k:'act',a:'peek',q:'观棋不语真君子。',f:'rune'},
            {n:'分身',k:'deathsave',q:'此身非我身。',f:'rune'}],
  '君倩':[{n:'君子',k:'atkLimit',v:1,q:'君子不争，争则必胜。',f:'sword'},
          {n:'倩',k:'reduce',v:1,c:'ru',q:'君子之交，淡如水。',f:'shield'}],
  '周澄':[{n:'澄',k:'jSwap',q:'澄澈见底，方见本心。',f:'scroll'},
          {n:'文',k:'judge',v:1,q:'文章千古事。',f:'scroll'}],
  '李宝瓶':[{n:'宝瓶',k:'draw',v:1,q:'宝瓶里装着好多问题。',f:'scroll'},
            {n:'问学',k:'act',a:'give',q:'我要问个明白！',f:'scroll'}],
  '林守一':[{n:'守一',k:'judge',v:1,q:'守一，而万事毕。',f:'scroll'},
            {n:'算',k:'judge',v:1,q:'算学一道，我最擅长。',f:'scroll'}],
  '张山峰':[{n:'山峰',k:'reduce',v:1,o:'once',q:'山就在那里。',f:'shield'},
            {n:'厚',k:'hand',v:1,q:'厚德载物。',f:'shield'}],
  '宋集薪':[{n:'集薪',k:'hand',v:2,q:'集薪，为的是烧得更旺。',f:'scroll'},
            {n:'弃文',k:'useAs',a:'any>basic',q:'文章，弃了也罢。',f:'scroll'}],
  '杨老头':[{n:'棋',k:'jChange',q:'落子无悔。',f:'rune'},
            {n:'师',k:'reduce',v:1,o:'once',q:'先生教过我的。',f:'shield'}],
  '李槐':[{n:'槐',k:'draw',v:1,q:'我李槐，也是要问学的。',f:'scroll'},
          {n:'问学',k:'act',a:'give',q:'先生，我有问题。',f:'scroll'}],
  '李希圣':[{n:'希圣',k:'draw',v:1,q:'希圣希贤，希天希道。',f:'scroll'},
            {n:'兄',k:'reduce',v:1,o:'turn',q:'妹妹莫怕，兄长在。',f:'shield'}],
  '赵繇':[{n:'繇印',k:'judge',v:1,q:'繇印在手，规矩在心。',f:'scroll'},
          {n:'静春',k:'reduce',v:1,o:'once',q:'先生的道理，我记着。',f:'shield'}],
  '宋长镜':[{n:'长镜',k:'atk',v:1,q:'大骊武夫，宋长镜。',f:'sword'},
            {n:'武运',k:'reduce',v:1,o:'turn',q:'武运昌隆。',f:'shield'}],

  /* ---------- 蛮荒天下 ---------- */
  zhoumi:[{n:'算计',k:'act',a:'suanji',q:'天下大局，尽在彀中。',f:'rune'},
          {n:'化外',k:'immune',v:'lang',q:'化外之地，无有王法。',f:'mist'}],
  baize:[{n:'通晓',k:'act',a:'peek',q:'天下万妖，我尽知晓。',f:'rune'},
         {n:'旁观',k:'reduce',v:1,o:'turn',q:'我只旁观，不动手。',f:'mist'}],
  '刘重润':[{n:'龙女',k:'deathsave',q:'龙女不死。',f:'lotus'},
            {n:'润',k:'act',a:'give',q:'润物细无声。',f:'lotus'}],
  '之祠':[{n:'神祠',k:'regen',v:1,q:'神祠受香火，自当庇护。',f:'lotus'},
          {n:'祠',k:'useAs',a:'trick>dodge',q:'祠中自有庇护。',f:'shield'}],
  '斐然':[{n:'画',k:'act',a:'forge',q:'画中自有天地。',f:'rune'},
          {n:'妖',k:'atk',v:1,c:'ru',q:'妖，本就该吃人。',f:'blood'}],
  '老瞎子':[{n:'盲',k:'nodist',q:'眼盲，心不盲。',f:'sword'},
            {n:'老',k:'reduce',v:1,o:'once',q:'活了这么久，还死不了。',f:'shield'}],
  '托月山':[{n:'山',k:'regen',v:1,q:'托月山，万年不动。',f:'aura'},
            {n:'托月',k:'reflect',v:1,o:'once',q:'伤我者，必受其反。',f:'blood'}],
  '纳兰烧苇':[{n:'烧苇',k:'atk',v:1,q:'一把火烧了这片苇荡。',f:'flame'},
              {n:'苇',k:'atk',v:1,c:'qing',q:'火借风势。',f:'flame'}],
  '老聋儿':[{n:'聋',k:'immune',v:'lang',q:'我听不见。',f:'aura'},
            {n:'儿',k:'hand',v:1,q:'老儿我，还硬朗。',f:'aura'}],
  '仰止':[{n:'仰',k:'range',v:1,q:'高山仰止。',qo:1,f:'aura'},
          {n:'止',k:'nododge',q:'景行行止。',qo:1,f:'sword'}],
  '龙君':[{n:'龙君',k:'auraAtk',v:1,c:'faction',q:'蛮荒之主，在此。',f:'mist'},
          {n:'君',k:'deathally',v:2,q:'蛮荒不灭。',f:'mist'}],
  '搬山猿':[{n:'搬山',k:'atk',v:1,q:'搬山！',f:'aura'},
            {n:'猿',k:'deathsave',q:'我乃正阳山供奉。',f:'aura'}],
  /* 旧十四王座·补齐十席 */
  '刘叉':[{n:'问剑',k:'nododge',q:'阿良，少不了你一剑。',f:'sword'},
          {n:'佩刀',k:'hitdraw',v:1,q:'刀在腰，剑在背。',f:'sword'}],
  '袁首':[{n:'搬山',k:'atk',v:1,q:'此山，我搬走了。',f:'aura'},
          {n:'石珠',k:'deathsave',q:'一子一山。',f:'aura'}],
  '五嶽':[{n:'六臂',k:'atkLimit',v:1,q:'三头六臂，各持一招。',f:'blood'},
          {n:'神到',k:'reduce',v:1,o:'turn',q:'陈清都那一剑，也未杀我。',f:'shield'}],
  '牛刀':[{n:'金甲',k:'reduce',v:1,o:'turn',q:'金甲是护甲，也是牢笼。',f:'shield'},
          {n:'蛮牛',k:'atk',v:1,q:'我也曾登过托月山。',f:'blood'}],
  '白莹':[{n:'枯骨',k:'deathally',v:1,q:'白骨堆成座，坐的是我。',f:'mist'},
          {n:'傀儡',k:'hand',v:1,q:'死人也能听令。',f:'mist'}],
  '绯妃':[{n:'水运',k:'regen',v:1,q:'天下水运，归我掌中。',f:'aura'},
          {n:'蛇蜕',k:'reduce',v:1,o:'once',q:'蜕一层皮，又是一条命。',f:'shield'}],
  '曜甲':[{n:'金精',k:'equipUp',v:1,q:'金精王座，天下最大的铜钱。',f:'forge'},
          {n:'倒悬',k:'reduce',v:1,o:'once',q:'山头朝地，山根朝天。',f:'shield'}],
  '切韵':[{n:'养剑葫',k:'hitextra',q:'葫里养的，都是剑仙。',f:'sword'},
          {n:'面皮',k:'immune',v:'lang',q:'这张脸，本不是我的。',f:'mist'}],
  '黄鸾':[{n:'洞府',k:'equipUp',v:1,q:'仙家洞府，我炼了一库。',f:'forge'},
          {n:'鸾翼',k:'range',v:1,q:'飞得高，才看得远。',f:'aura'}],
  '荷花庵主':[{n:'月魄',k:'regen',v:1,q:'蛮荒三月，我取其半。',f:'aura'},
              {n:'庵主',k:'judge',v:1,q:'贫道坐于此。',f:'lotus'}],

  /* ---------- 青冥天下 ---------- */
  daozu:[{n:'道法自然',k:'act',a:'daoziran',q:'道法自然。',qo:1,f:'rune'},
         {n:'无为',k:'reduce',v:1,o:'turn',q:'无为而无不为。',qo:1,f:'aura'}],
  '余斗':[{n:'斗转',k:'judge',v:1,q:'斗转星移。',f:'star'},
          {n:'星移',k:'range',v:1,q:'星移物换。',f:'star'}],
  '陆沉':[{n:'一气化三清',k:'act',a:'sanqing',q:'一气化三清。',qo:1,f:'rune'},
          {n:'沉静',k:'judge',v:1,q:'沉静如水。',f:'aura'}],
  '南簪':[{n:'簪',k:'draw',v:1,q:'一支簪子，也能杀人。',f:'sword'},
          {n:'南',k:'hand',v:1,q:'南簪，南簪。',f:'aura'}],
  '卢白象':[{n:'白象',k:'reduce',v:1,o:'turn',q:'白象负重，行稳致远。',f:'shield'},
            {n:'卢',k:'atk',v:1,c:'mang',q:'卢氏武夫，白象在身。',f:'blood'}],
  '刘灞桥':[{n:'灞桥',k:'reduce',v:1,o:'turn',q:'灞桥折柳，送君千里。',f:'shield'}],
  '谢松花':[{n:'松花',k:'regen',v:1,q:'松花酿酒，春水煎茶。',f:'lotus'},
            {n:'谢',k:'hand',v:1,q:'谢家的女儿。',f:'aura'}],
  '谢狗':[{n:'狗',k:'atk',v:1,c:'low',q:'狗急了，也咬人。',f:'blood'}],
  '贺小凉':[{n:'小凉',k:'jReroll',q:'小凉，凉的是心。',f:'shield'}],
  '赊月':[{n:'赊',k:'draw',v:1,q:'赊月色，赊风声。',f:'aura'}],
  '郑居中':[{n:'居中',k:'judge',v:1,q:'居中，则不偏不倚。',f:'scroll'},
            {n:'郑',k:'hand',v:1,q:'郑居中，居中而立。',f:'aura'}],
  '郭竹酒':[{n:'竹酒',k:'regen',v:1,q:'竹酒一壶，敬此山河。',f:'lotus'},
            {n:'郭',k:'draw',v:1,q:'郭家的酒，管够。',f:'aura'}],
  '长命':[{n:'长命',k:'deathsave',q:'长命，长命百岁。',f:'lotus'}],
  '徐远霞':[{n:'远霞',k:'range',v:1,q:'远霞孤鹜，秋水长天。',f:'sword'},
            {n:'徐',k:'hand',v:1,q:'徐徐图之。',f:'aura'}],
  '小陌':[{n:'陌',k:'draw',v:1,q:'陌上花开，可缓缓归矣。',f:'lotus'}],
  '苏稼':[{n:'稼',k:'regen',v:1,q:'耕读传家，稼穑为本。',f:'lotus'}],
  '裴杯':[{n:'杯',k:'act',a:'give',q:'一杯酒，敬同道。',f:'aura'}],
  '陈景清':[{n:'景清',k:'judge',v:1,q:'景清，心清。',f:'scroll'}],
  '陈暖树':[{n:'暖树',k:'regen',v:1,q:'暖树栖鸦，各自安好。',f:'lotus'}],
  '隋景澄':[{n:'景澄',k:'reduce',v:1,o:'turn',q:'景澄，心澄。',f:'shield'},
            {n:'隋',k:'flavor',q:'隋家的人，不后退。',f:'shield'}],
  '魏檗':[{n:'山君',k:'reduce',v:1,o:'turn',q:'山君在此，百兽退避。',f:'aura'},
          {n:'檗',k:'atk',v:1,c:'mang',q:'檗木虽苦，可斩妖邪。',f:'blood'}],
  '魏羡':[{n:'羡',k:'draw',v:1,q:'羡，是羡慕，也是多余。',f:'aura'}],
  '黄庭':[{n:'黄庭',k:'equipUp',v:1,q:'黄庭一卷，诵读不辍。',f:'scroll'}],
  '周海镜':[{n:'海镜',k:'act',a:'peek',q:'海镜照心，无所遁形。',f:'rune'}],
  '周米粒':[{n:'米粒',k:'draw',v:1,q:'米粒虽小，也能果腹。',f:'aura'}],
  '石柔':[{n:'蜕',k:'reduce',v:1,o:'once',q:'这身皮囊，原是替人挡灾用的。',f:'shield'},
          {n:'窥',k:'judge',v:1,q:'这双眼睛，曾被人借去看落魄山。',f:'aura'}],
  '稚圭':[{n:'稚圭',k:'regen',v:1,q:'稚圭，稚圭。',f:'lotus'}],
  '宋雨烧':[{n:'雨烧',k:'atk',v:1,q:'雨中烧火，烧不尽。',f:'flame'}],
  '沛湘':[{n:'沛',k:'draw',v:1,q:'沛然莫御。',f:'aura'},
          {n:'湘',k:'hand',v:1,q:'湘水悠悠。',f:'aura'}],
  '柳柔':[{n:'柔',k:'reduce',v:1,o:'turn',q:'柔，是柳的本分。',f:'shield'}],
  '陆台':[{n:'陆台',k:'judge',v:1,q:'陆台高筑，望远。',f:'scroll'}],
  '马苦玄':[{n:'苦玄',k:'reduce',v:1,o:'turn',q:'苦，是修行的本分。',f:'shield'},
            {n:'玄',k:'judge',v:1,q:'玄之又玄，众妙之门。',qo:1,f:'rune'}],
  '于玄':[{n:'于玄',k:'judge',v:1,q:'于玄，于玄。',f:'rune'}],
  '吴霜降':[{n:'霜降',k:'atk',v:1,c:'low',q:'霜降，则万物收藏。',f:'sword'}],
  '苏心斋':[{n:'心斋',k:'immune',v:'lang',q:'心斋坐忘。',qo:1,f:'aura'}],
  '郦彩':[{n:'郦彩',k:'draw',v:1,q:'郦彩，郦彩。',f:'aura'}],
  '阮邛':[{n:'铸剑',k:'startequip',q:'铸剑师阮邛，在此。',f:'forge'},
          {n:'护女',k:'reduce',v:1,o:'turn',q:'谁敢动我女儿。',f:'shield'}],
  '蔡金简':[{n:'断桥',k:'atk',v:1,q:'长生桥，断。',f:'sword'},
            {n:'金简',k:'nododge',q:'正阳山蔡金简。',f:'sword'}],
  '董水井':[{n:'井',k:'draw',v:1,q:'井水不犯河水。',f:'aura'},
            {n:'商',k:'hand',v:1,q:'商人重利，也重义。',f:'aura'}],
  '顾粲':[{n:'棋子',k:'act',a:'qizi',q:'哥，我下棋从没输过。',f:'rune'},
          {n:'蛊',k:'reflect',v:1,o:'once',q:'书简湖的规矩，是弱肉强食。',f:'blood'}],
  liulaocheng:[{n:'书简湖',k:'hand',v:1,q:'湖里的规矩，不是一天立起来的。',f:'aura'},
               {n:'老成',k:'judge',v:1,q:'老成，是活出来的。',f:'scroll'}],
  liujinglong:[{n:'规矩',k:'nodist',q:'规矩既定，剑不可挡。',f:'sword'},
               {n:'守序',k:'taunt',q:'同袍有难，我来。',f:'aura'}],
  '萧愻':[{n:'愻',k:'hitextra',q:'一剑未尽，再来一剑。',f:'sword'}],
  xunyuan:[{n:'一尺枪',k:'atk',v:1,q:'一尺枪，一寸短一寸险。',f:'sword'},
           {n:'余家贫',k:'reduce',v:1,o:'turn',q:'余家贫，守得住。',f:'shield'}],
  yuyue:[{n:'惊鸟',k:'range',v:1,q:'惊鸟一飞，电抹长空。',f:'sword'},
         {n:'百花',k:'hand',v:1,q:'百花满江河。',f:'sword'}],

  /* ---------- 落魄山（后补 · 原著可考） ---------- */
  '曹晴朗':[{n:'三元',k:'draw',v:1,q:'',f:'scroll'},
            {n:'读书',k:'judge',v:1,q:'',f:'aura'}],
  '赵树下':[{n:'百万拳',k:'atk',v:1,q:'',f:'aura'},
            {n:'走桩',k:'draw',v:1,q:'',f:'aura'}],
  '宁吉':[{n:'道胎',k:'draw',v:1,q:'',f:'rune'},
          {n:'开卷',k:'judge',v:1,q:'',f:'scroll'}],
  '邓剑枰':[{n:'开山',k:'atk',v:1,q:'',f:'sword'},
            {n:'文脉',k:'judge',v:1,q:'',f:'scroll'}],
  '袁黄':[{n:'金身',k:'reduce',v:1,q:'',f:'shield'},
          {n:'诚拳',k:'atk',v:1,q:'',f:'aura'}],
  '郑大风':[{n:'守门',k:'reduce',v:1,q:'',f:'shield'},
            {n:'大霜',k:'draw',v:1,q:'',f:'aura'}],
  '韦文龙':[{n:'术算',k:'draw',v:1,q:'',f:'rune'},
            {n:'泉府',k:'hand',v:1,q:'',f:'aura'}],

  '郭稼':[{n:'家剑',k:'atk',v:1,c:'mang',q:'',f:'sword'},{n:'祭奠',k:'act',q:'',f:'aura'}],
  '叠嶂':[{n:'酒铺',k:'draw',v:1,q:'',f:'lotus'},{n:'叠嶂',k:'act',q:'',f:'aura'}],
  '观照':[{n:'问剑',k:'act',q:'',f:'sword'},{n:'托月',k:'atk',v:2,o:'once',q:'',f:'sword'}],
  '陈淳安':[{n:'陪都',k:'reduce',v:1,o:'turn',q:'',f:'shield'},{n:'打落',k:'atk',v:2,o:'once',c:'mang',q:'',f:'blood'}],
  '邵云岩':[{n:'倒悬',k:'draw',v:1,q:'',f:'scroll'},{n:'嫡传',k:'judge',v:1,c:{with:'陈平安'},q:'',f:'aura'}],
  '种秋':[{n:'种',k:'act',q:'',f:'lotus'},{n:'秋',k:'judge',v:1,q:'',f:'scroll'}],
  '刘志茂':[{n:'书简',k:'act',q:'',f:'rune'},{n:'看中',k:'atk',v:1,c:{with:'顾粲'},q:'',f:'blood'}],
  '嫩道人':[{n:'嫩',k:'reduce',v:1,o:'turn',q:'',f:'shield'},{n:'护道',k:'hand',v:1,c:{with:'李槐'},q:'',f:'aura'}],
  '邓剑翘':[{n:'翘',k:'reduce',v:1,o:'turn',q:'',f:'shield'},{n:'拳',k:'atk',v:1,q:'',f:'blood'}],
  '赵鸾':[{n:'鸾',k:'dodgeAs',q:'',f:'shield'},{n:'妹',k:'hand',v:1,c:{with:'赵树下'},q:'',f:'aura'}],
  '陈对':[{n:'颍阴',k:'draw',v:1,q:'',f:'lotus'},{n:'救',k:'deathsave',q:'',f:'lotus'}],
  '离真':[{n:'天骄',k:'atk',v:1,q:'',f:'blood'},{n:'离',k:'deathsave',q:'',f:'mist'}],
  '姚冲道':[{n:'冲道',k:'atk',v:1,q:'',f:'sword'},{n:'联手',k:'hand',v:1,c:{with:'阿良'},q:'',f:'aura'}],
  '顾佑':[{n:'佑',k:'reduce',v:1,o:'turn',q:'',f:'shield'},{n:'止境',k:'atk',v:1,q:'',f:'blood'}],
};

const TALENT_DESC = {
  '锋芒':'剑气长城天赋：你每回合首次打出的「剑气」伤害 +1。',
  '耕读':'中土文庙天赋：摸牌阶段额外摸 1 张。',
  '嗜血':'蛮荒天下天赋：你每回合首次造成伤害后，回复 1 点气血。',
  '无为':'青冥天下天赋：你每回合首次受到的伤害 -1。',
  '慈悲':'莲花天下天赋：你的「丹药」回复 2 点气血。',
  '机缘':'散修天赋：你每回合首次打出「锦囊」后，摸 1 张。',
};

const CARD_SIG = {
  '剑气':'剑', '守心':'守', '丹药':'丹', '饮者':'酒', '本命飞剑':'器',
  '论道':'论', '万剑归宗':'万', '蛮荒入侵':'蛮', '破阵':'破', '借物':'借',
  '天劫':'劫', '读书':'书', '炼器':'炼',
};

const CARD_KIND = { attack:'基本·攻', dodge:'基本·守', heal:'基本·丹', wine:'基本·酒', trick:'锦囊', equip:'装备' };

const SHOUTS = {
  attack:['一剑霜寒','长剑出鞘','剑气纵横','斩浪式','破云斩','问剑于野','横剑四顾'],
  dodge:['守心如玉','不动如山','气定神闲'],
  heal:['丹田回暖','回春之息'],
  wine:['且饮此杯'],
  equip:['本命飞剑·出鞘'],
  trick:{ duel:'与你论道', wanjian:'万剑归宗', nanman:'蛮荒入侵', pozhen:'破阵子',
          jiewu:'借物代形', tianjie:'天劫降世', dushu:'读书养气', lianqi:'祭炼飞剑' },
};

const MODE_META = {
  hot:   { title:'群雄论剑', minPick:2, maxPick:5 },
  ai:    { title:'仗剑独行', minPick:1, maxPick:1 },
  siege: { title:'剑气长城', minPick:1, maxPick:3 },
  boss:  { title:'天下共伐', minPick:2, maxPick:3 },
};

const BG_LIST = ['hepan.png','feisheng.png','一句一剑仙.png'];

function shuffle(a){ for(let i=a.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]; } return a; }
function cardPoint(c){ return ({ dodge:2, heal:1, attack:3, wine:4, trick:5, equip:4 })[c.type] || 3; }
function pickShout(list){ return list[Math.floor(Math.random()*list.length)]; }
function parseSkills(txt){
  if(!txt) return [];
  const out=[]; const re=/【([^】]+)】([^【]*)/g; let m;
  while((m=re.exec(txt))) out.push({ name:m[1], desc:m[2].replace(/^[；;、\s]+/,'') .trim() });
  return out;
}
function cardSig(c){ return CARD_SIG[c.name] || c.name.charAt(0); }
function cardCls(c){ return ({attack:'c-attack',dodge:'c-dodge',heal:'c-heal',wine:'c-wine',trick:'c-trick',equip:'c-equip'})[c.type]||''; }

// 图片基址：部署到公网/CDN 后改成你的地址，例如 'https://your-cdn.com/jianlai'。
// 留空时小程序内显示阵营色占位（无立绘），等你有托管再填。
const IMG_BASE = '';
// 有立绘的 key（由 gen_data.js 扫 weapp/packageArt/assets/portraits 目录生成，勿手改）
const HAS_PORTRAIT = new Set(["aliang","baiye","baize","caoci","chenpingan","chenqingdu","daozu","fozu","lisan","miyu","ningyao","qijingchun","zhoumi","之祠","于玄","五嶽","亚圣","仙尉","仰止","余斗","切韵","刘叉","刘志茂","刘灞桥","刘羡阳","刘重润","初升","南簪","卢白象","叠嶂","君倩","吴霜降","周海镜","周澄","周米粒","姚近之","姜尚真","姜赦","嫩道人","宋集薪","宋雨烧","寇名","小陌","崔东山","崔瀺","崔诚","左右","张山峰","徐远霞","托月山大祖","持剑者","斐然","新妆","曹晴朗","朱敛","朱敛真容","李二","李宝瓶","李希圣","李柳","李槐","杨老头","林守一","柔荑","柳柔","沛湘","火龙真人","牛刀","白莹","种秋","稚圭","米裕","绯妃","老秀才","至圣先师","苏心斋","苏稼","荷花庵主","萧愻","董三更","蔡金简","袁首","裴杯","裴钱","观照","谢松花","谢狗","贺小凉","赊月","赵天籁","路人","邵云岩","郑居中","郦彩","郭稼","郭竹酒","长命","阮秀","陆台","陆沉","陆芝","陈景清","陈暖树","陈淳安","隋右边","隋景澄","顾璨","顾粲","马苦玄","魏晋","魏檗","魏羡","黄庭","黄鸾","齐廷济","齐景龙","龙君"]);
function portraitKey(key){ return String(key).replace(/[\/\\:]/g,'_'); }
function artUrl(key){
  if(IMG_BASE) return IMG_BASE + '/art/' + key + '.png';
  const k = portraitKey(key);
  return HAS_PORTRAIT.has(k) ? ('/packageArt/assets/portraits/' + k + '.jpg') : '';
}
function bgUrl(name){ return IMG_BASE ? IMG_BASE + '/bg/' + name : ''; }
module.exports = { FACTIONS, HOSTILE, CHARS, REALM_LIMIT, SKILLS, TALENT_DESC, CARD_SIG, CARD_KIND, cardSig, cardCls, SHOUTS, MODE_META, BG_LIST, IMG_BASE, HAS_PORTRAIT, artUrl, bgUrl, shuffle, cardPoint, pickShout, parseSkills };
